//@version=6
indicator(shorttitle="BB 1s2s3s", title="Bollinger Bands Multi Sigma", overlay=true, timeframe="", timeframe_gaps=true)

length = input.int(20, "Length", minval=1)
maType = input.string("SMA", "Basis MA Type", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
src    = input(close, "Source")
offset = input.int(0, "Offset", minval=-500, maxval=500, display=display.none)

ma(source, length, _type) =>
    switch _type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

basis = ma(src, length, maType)
dev   = ta.stdev(src, length)

// プロット - 中心線
plot(basis, "SMA", color.red, 2, offset=offset)

// 1s（明るい緑）
plot(basis + dev,     "+1s", color.new(color.lime, 0), offset=offset)
plot(basis - dev,     "-1s", color.new(color.lime, 0), offset=offset)

// 2s（中間の緑）
plot(basis + dev * 2, "+2s", color.new(color.lime, 30), offset=offset)
plot(basis - dev * 2, "-2s", color.new(color.lime, 30), offset=offset)

// 3s（薄い緑）
plot(basis + dev * 3, "+3s", color.new(color.lime, 55), offset=offset)
plot(basis - dev * 3, "-3s", color.new(color.lime, 55), offset=offset)
